<?php

namespace ContainerTwLFhu1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8L9Dm7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8L9Dm7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8L9Dm7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['services', 'App\\Repository\\BlogPostRepository', 'getBlogPostRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'user' => ['privates', '.errored..service_locator.8L9Dm7h.App\\Entity\\AppUser', NULL, 'Cannot autowire service ".service_locator.8L9Dm7h": it needs an instance of "App\\Entity\\AppUser" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repo' => 'App\\Repository\\BlogPostRepository',
            'serializer' => '?',
            'user' => 'App\\Entity\\AppUser',
        ]);
    }
}
