<?php

namespace ContainerPi8V2UZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5T_UpY_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5T.UpY.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5T.UpY.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogPostController::addBlog' => ['privates', '.service_locator.r682ukv', 'get_ServiceLocator_R682ukvService', true],
            'App\\Controller\\BlogPostController::addComment' => ['privates', '.service_locator.1MKZjV2', 'get_ServiceLocator_1MKZjV2Service', true],
            'App\\Controller\\BlogPostController::deleteBlogPost' => ['privates', '.service_locator.uIhlHo0', 'get_ServiceLocator_UIhlHo0Service', true],
            'App\\Controller\\BlogPostController::editBlog' => ['privates', '.service_locator.xcCKT4K', 'get_ServiceLocator_XcCKT4KService', true],
            'App\\Controller\\BlogPostController::followPosts' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\BlogPostController::retrieveAllBlog' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\BlogPostController::retrieveSingleBlog' => ['privates', '.service_locator.cIvhbp5', 'get_ServiceLocator_CIvhbp5Service', true],
            'App\\Controller\\BlogPostController::topLiked' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\FollowersController::follow' => ['privates', '.service_locator.gEOpjwz', 'get_ServiceLocator_GEOpjwzService', true],
            'App\\Controller\\FollowersController::unFollow' => ['privates', '.service_locator.hRnhTRv', 'get_ServiceLocator_HRnhTRvService', true],
            'App\\Controller\\LikeController::like' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LikeController::unlike' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\ProfileController::followers' => ['privates', '.service_locator.nOJnvwk', 'get_ServiceLocator_NOJnvwkService', true],
            'App\\Controller\\ProfileController::following' => ['privates', '.service_locator.nOJnvwk', 'get_ServiceLocator_NOJnvwkService', true],
            'App\\Controller\\ProfileController::show' => ['privates', '.service_locator.8L9Dm7h', 'get_ServiceLocator_8L9Dm7hService', true],
            'App\\Controller\\ProfileSettingController::profile' => ['privates', '.service_locator.Zk4_73s', 'get_ServiceLocator_Zk473sService', true],
            'App\\Controller\\ProfileSettingController::profileImage' => ['privates', '.service_locator.sfEME4w', 'get_ServiceLocator_SfEME4wService', true],
            'App\\Controller\\ProfileSettingController::updateUserProfile' => ['privates', '.service_locator.GYRAYNX', 'get_ServiceLocator_GYRAYNXService', true],
            'App\\Controller\\UserController::confirmEmail' => ['privates', '.service_locator.T1d6F8j', 'get_ServiceLocator_T1d6F8jService', true],
            'App\\Controller\\UserController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::register' => ['privates', '.service_locator.XttDSVG', 'get_ServiceLocator_XttDSVGService', true],
            'App\\Controller\\UserController::resetPassword' => ['privates', '.service_locator.VNfh.KW', 'get_ServiceLocator_VNfh_KWService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlogPostController:addBlog' => ['privates', '.service_locator.r682ukv', 'get_ServiceLocator_R682ukvService', true],
            'App\\Controller\\BlogPostController:addComment' => ['privates', '.service_locator.1MKZjV2', 'get_ServiceLocator_1MKZjV2Service', true],
            'App\\Controller\\BlogPostController:deleteBlogPost' => ['privates', '.service_locator.uIhlHo0', 'get_ServiceLocator_UIhlHo0Service', true],
            'App\\Controller\\BlogPostController:editBlog' => ['privates', '.service_locator.xcCKT4K', 'get_ServiceLocator_XcCKT4KService', true],
            'App\\Controller\\BlogPostController:followPosts' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\BlogPostController:retrieveAllBlog' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\BlogPostController:retrieveSingleBlog' => ['privates', '.service_locator.cIvhbp5', 'get_ServiceLocator_CIvhbp5Service', true],
            'App\\Controller\\BlogPostController:topLiked' => ['privates', '.service_locator.GLXEf8M', 'get_ServiceLocator_GLXEf8MService', true],
            'App\\Controller\\FollowersController:follow' => ['privates', '.service_locator.gEOpjwz', 'get_ServiceLocator_GEOpjwzService', true],
            'App\\Controller\\FollowersController:unFollow' => ['privates', '.service_locator.hRnhTRv', 'get_ServiceLocator_HRnhTRvService', true],
            'App\\Controller\\LikeController:like' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LikeController:unlike' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\ProfileController:followers' => ['privates', '.service_locator.nOJnvwk', 'get_ServiceLocator_NOJnvwkService', true],
            'App\\Controller\\ProfileController:following' => ['privates', '.service_locator.nOJnvwk', 'get_ServiceLocator_NOJnvwkService', true],
            'App\\Controller\\ProfileController:show' => ['privates', '.service_locator.8L9Dm7h', 'get_ServiceLocator_8L9Dm7hService', true],
            'App\\Controller\\ProfileSettingController:profile' => ['privates', '.service_locator.Zk4_73s', 'get_ServiceLocator_Zk473sService', true],
            'App\\Controller\\ProfileSettingController:profileImage' => ['privates', '.service_locator.sfEME4w', 'get_ServiceLocator_SfEME4wService', true],
            'App\\Controller\\ProfileSettingController:updateUserProfile' => ['privates', '.service_locator.GYRAYNX', 'get_ServiceLocator_GYRAYNXService', true],
            'App\\Controller\\UserController:confirmEmail' => ['privates', '.service_locator.T1d6F8j', 'get_ServiceLocator_T1d6F8jService', true],
            'App\\Controller\\UserController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:register' => ['privates', '.service_locator.XttDSVG', 'get_ServiceLocator_XttDSVGService', true],
            'App\\Controller\\UserController:resetPassword' => ['privates', '.service_locator.VNfh.KW', 'get_ServiceLocator_VNfh_KWService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlogPostController::addBlog' => '?',
            'App\\Controller\\BlogPostController::addComment' => '?',
            'App\\Controller\\BlogPostController::deleteBlogPost' => '?',
            'App\\Controller\\BlogPostController::editBlog' => '?',
            'App\\Controller\\BlogPostController::followPosts' => '?',
            'App\\Controller\\BlogPostController::retrieveAllBlog' => '?',
            'App\\Controller\\BlogPostController::retrieveSingleBlog' => '?',
            'App\\Controller\\BlogPostController::topLiked' => '?',
            'App\\Controller\\FollowersController::follow' => '?',
            'App\\Controller\\FollowersController::unFollow' => '?',
            'App\\Controller\\LikeController::like' => '?',
            'App\\Controller\\LikeController::unlike' => '?',
            'App\\Controller\\ProfileController::followers' => '?',
            'App\\Controller\\ProfileController::following' => '?',
            'App\\Controller\\ProfileController::show' => '?',
            'App\\Controller\\ProfileSettingController::profile' => '?',
            'App\\Controller\\ProfileSettingController::profileImage' => '?',
            'App\\Controller\\ProfileSettingController::updateUserProfile' => '?',
            'App\\Controller\\UserController::confirmEmail' => '?',
            'App\\Controller\\UserController::login' => '?',
            'App\\Controller\\UserController::register' => '?',
            'App\\Controller\\UserController::resetPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlogPostController:addBlog' => '?',
            'App\\Controller\\BlogPostController:addComment' => '?',
            'App\\Controller\\BlogPostController:deleteBlogPost' => '?',
            'App\\Controller\\BlogPostController:editBlog' => '?',
            'App\\Controller\\BlogPostController:followPosts' => '?',
            'App\\Controller\\BlogPostController:retrieveAllBlog' => '?',
            'App\\Controller\\BlogPostController:retrieveSingleBlog' => '?',
            'App\\Controller\\BlogPostController:topLiked' => '?',
            'App\\Controller\\FollowersController:follow' => '?',
            'App\\Controller\\FollowersController:unFollow' => '?',
            'App\\Controller\\LikeController:like' => '?',
            'App\\Controller\\LikeController:unlike' => '?',
            'App\\Controller\\ProfileController:followers' => '?',
            'App\\Controller\\ProfileController:following' => '?',
            'App\\Controller\\ProfileController:show' => '?',
            'App\\Controller\\ProfileSettingController:profile' => '?',
            'App\\Controller\\ProfileSettingController:profileImage' => '?',
            'App\\Controller\\ProfileSettingController:updateUserProfile' => '?',
            'App\\Controller\\UserController:confirmEmail' => '?',
            'App\\Controller\\UserController:login' => '?',
            'App\\Controller\\UserController:register' => '?',
            'App\\Controller\\UserController:resetPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
