<?php

namespace Container87PKwvx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VPCq8VaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vPCq8Va' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vPCq8Va'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repo' => ['services', 'App\\Repository\\BlogPostRepository', 'getBlogPostRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'imageService' => 'App\\Service\\ImageService',
            'logger' => '?',
            'repo' => 'App\\Repository\\BlogPostRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
