<?php

namespace Container87PKwvx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jf_T4EHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jf.t4EH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jf.t4EH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.jf.t4EH.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.jf.t4EH": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'blog' => 'App\\Entity\\BlogPost',
            'entityManager' => '?',
            'imageService' => 'App\\Service\\ImageService',
            'logger' => '?',
            'security' => '?',
            'validator' => '?',
        ]);
    }
}
