<?php

namespace Container87PKwvx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPost4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jf.t4EH.App\Entity\BlogPost' shared service.
     *
     * @return \App\Entity\BlogPost
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jf.t4EH": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".');
    }
}
