<?php

namespace ContainerWrO2Mxk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CIvhbp5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cIvhbp5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cIvhbp5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.cIvhbp5.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.cIvhbp5": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
        ], [
            'blog' => 'App\\Entity\\BlogPost',
        ]);
    }
}
