<?php

namespace Container3aQwsc6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GLXEf8MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GLXEf8M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GLXEf8M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['services', 'App\\Repository\\BlogPostRepository', 'getBlogPostRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\BlogPostRepository',
        ]);
    }
}
