services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Service definitions
    App\Service\BlogPostFormatter: ~    
    App\Service\ImgurService: ~ # Ensure the class name is correctly cased

    # Makes classes in src/ available to be used as services
    # This creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\:
        resource: '../src/Repository'
        public: true
        tags: ['doctrine.repository_service']

    # Add more service definitions when explicit configuration is needed
    # Please note that last definitions always *replace* previous ones

    App\Security\JWTManager:
        arguments:
            - '@lexik_jwt_authentication.encoder'
            - '@event_dispatcher'
        public: true

    App\Service\TokenGenerator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
