parameters:
    profiles: '/uploads/profiles/'
    profiles_directory: '%kernel.project_dir%/public%profiles%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    GuzzleHttp\Client: ~

    App\Service\BlogPostFormatter: ~    
    App\Service\ImageService:
        arguments:
            $client: '@GuzzleHttp\Client'
            $logger: '@logger'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\:
        resource: '../src/Repository'
        public: true
        tags: ['doctrine.repository_service']

    App\Security\JWTManager:
        arguments:
            - '@lexik_jwt_authentication.encoder'
            - '@event_dispatcher'
        public: true

    App\Service\TokenGenerator:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
