<?php

namespace Container2URxuye;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppUser2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gEOpjwz.App\Entity\AppUser' shared service.
     *
     * @return \App\Entity\AppUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gEOpjwz": it needs an instance of "App\\Entity\\AppUser" but this type has been excluded in "config/services.yaml".');
    }
}
