<?php

namespace ContainerAEGH40a;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NOJnvwkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nOJnvwk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nOJnvwk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['services', 'App\\Repository\\AppUserRepository', 'getAppUserRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.nOJnvwk.App\\Entity\\AppUser', NULL, 'Cannot autowire service ".service_locator.nOJnvwk": it needs an instance of "App\\Entity\\AppUser" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repo' => 'App\\Repository\\AppUserRepository',
            'user' => 'App\\Entity\\AppUser',
        ]);
    }
}
