<?php

namespace ContainerNIgnkO8;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3YNzoIJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3YNzoIJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3YNzoIJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.3YNzoIJ.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.3YNzoIJ": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['privates', '.errored..service_locator.3YNzoIJ.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.3YNzoIJ": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'imageService' => ['privates', 'App\\Service\\ImageService', 'getImageServiceService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repo' => ['services', 'App\\Repository\\BlogPostRepository', 'getBlogPostRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'blog' => 'App\\Entity\\BlogPost',
            'entityManager' => 'Doctrine\\ORM\\EntityManager',
            'imageService' => 'App\\Service\\ImageService',
            'logger' => '?',
            'repo' => 'App\\Repository\\BlogPostRepository',
            'security' => '?',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
