<?php

namespace ContainerZm608Jl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SfEME4wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sfEME4w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sfEME4w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'repo' => ['services', 'App\\Repository\\AppUserRepository', 'getAppUserRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'logger' => '?',
            'repo' => 'App\\Repository\\AppUserRepository',
            'slugger' => '?',
            'validator' => '?',
        ]);
    }
}
