<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPi8V2UZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPi8V2UZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPi8V2UZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPi8V2UZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPi8V2UZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pi8V2UZ',
    'container.build_id' => '56f3ddee',
    'container.build_time' => 1722424595,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPi8V2UZ');
