<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3j0uDvZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3j0uDvZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3j0uDvZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3j0uDvZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3j0uDvZ\App_KernelDevDebugContainer([
    'container.build_hash' => '3j0uDvZ',
    'container.build_id' => '96369c6a',
    'container.build_time' => 1722251765,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3j0uDvZ');
