<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3aQwsc6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3aQwsc6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3aQwsc6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3aQwsc6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3aQwsc6\App_KernelDevDebugContainer([
    'container.build_hash' => '3aQwsc6',
    'container.build_id' => '4df178a7',
    'container.build_time' => 1722583377,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3aQwsc6');
