<?php

namespace ContainerLTswEOk;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8L9Dm7h.App\Entity\AppUser' shared service.
     *
     * @return \App\Entity\AppUser
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8L9Dm7h": it needs an instance of "App\\Entity\\AppUser" but this type has been excluded in "config/services.yaml".');
    }
}
